### ISSUE TITLE
Struct viewer drops zeros after the decimal point for the time field 

### ISSUE THREAD

**Issue by lmedagoda** [rock-core/gui-vizkit#52]
I noticed that the time shown in the struct-viewer didn't show a zero after the decimal point, and seemingly gave some measurements out of order. Cross-checked with a .csv of the log, and the time was shown correctly there.

For example:

Time in struct_viewer: 15:32.1234
Time in .csv for the same measurement: 15:32.01234

**Comment by goldhoorn** [comment]
On 22.10.2015 11:33, lmedagoda wrote:
>
> I noticed that the time shown in the struct-viewer didn't show a zero
> after the decimal point, and seemingly gave some measurements out of
> order. Cross-checked with a .csv of the log, and the time was shown
> correctly there.
>
On which branch do you working, this should be fixed by:

https://github.com/rock-core/gui-vizkit/pull/41

on master

-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by lmedagoda** [comment]
Thanks, switching to master fixes it.
